---
- hosts: all
  become: yes
  gather_facts: yes

  vars:
    docker_users:
      - vagrant
    go_custom_mirror: https://storage.googleapis.com/golang
    go_version: 1.12.5
    GOPATH: /home/vagrant/go
    GOROOT: /usr/local/go
    GOPROXY: https://proxy.golang.org

  roles:
    - andrewrothstein.anaconda
    - fubarhouse.golang
    - geerlingguy.nfs
    - geerlingguy.packer-rhel
    - wtanaka.gcloud_sdk
    - andrewrothstein.kubectl
    - geerlingguy.docker
    - andrewrothstein.cfssl
